name: CoordsOffline
version: 2.0.0
main: org.elliotnash.coordsoffline.CoordsOfflinePlugin
api-version: 1.21
author: Elliot
description: A plugin to view the coordinates of a player who's offline or online.
commands:
  coords:
    usage: /coords player
    description: Find the coords of a player
    permission: coordsoffline.use
  otp:
    usage: /otp [source] target
    description: Teleports a player (including offline players)
    permission: coordsoffline.teleport
permissions:
  coordsoffline.use:
    description: Allows use of the /coords command
    default: op
  coordsoffline.teleport:
    description: Allows use of the /otp command
    default: op