name: CordsOffline
version: ${project.version}
main: cordsoffline.cordsoffline.CordsOffline
api-version: 1.13
authors: [Elliot]
description: Get a players coords even if they are offline
website: www.elliotnash.org
commands:
  coords:
    permission: coords.get