name: Main
version: ${project.version}
main: cordsoffline.main.Main
api-version: 1.13
commands:
  coords:
    usage: /coords player
    description: Find the coords of a player
    permission: coordsoffline.use
